#! /usr/bin/env python

# Zeobuilder is an extensible GUI-toolkit for molecular model construction.
# Copyright (C) 2005 Toon Verstraelen
# 
# This file is part of Zeobuilder.
# 
# Zeobuilder is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
# 
# --


import pygtk, sys
pygtk.require('2.0')


def init_fn_nothing():
    pass

def init_fn_new():
    from zeobuilder import context
    FileNew = context.application.plugins.get_action("FileNew")
    FileNew()

class InitFnOpen:
    def __init__(self, filename):
        self.filename = filename
        
    def __call__(self):
        from zeobuilder import context
        from zeobuilder.models import FilenameError
        from zeobuilder.filters import FilterError
        import gtk
        try:
            context.application.model.file_open(self.filename)
        except (FilenameError, FilterError), e:
            print str(e)    
            gtk.main_quit()
            sys.exit(2)

usage="""Usage: zeobuilder [-nofile|filename]
Zeobuilder is an extensible GUI-toolkit for molecular model construction.

Arguments:
  -nofile     Do not initialize the model. (Only usefull for debugging)
  filename    The name of a file to open after zeobuilder has started.
"""

if len(sys.argv) == 1:
    init_fn = init_fn_new
elif len(sys.argv) == 2:
    if sys.argv[1] == "-nofile":
        init_fn = init_fn_nothing
    else:
        init_fn = InitFnOpen(sys.argv[1])
else:
    print usage
    sys.exit(1)

from zeobuilder.application import Application
Application([init_fn])
